# Generated by Django 5.1 on 2024-09-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_longitide_airport_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='date_of_birth',
            new_name='birthday',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='phone_number',
        ),
    ]
