# Generated by Django 5.1.1 on 2024-10-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='birthday',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Unknown', max_length=6),
        ),
    ]
