# Generated by Django 5.1 on 2024-09-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_country_rename_date_of_birth_passenger_birthday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='email',
        ),
        migrations.AddField(
            model_name='passenger',
            name='citizenship',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='passenger',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Unknown', max_length=1),
        ),
    ]
