# Generated by Django 5.1.1 on 2024-10-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_passenger_birthday_alter_passenger_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightprice',
            name='price_history',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
