# Generated by Django 5.1.1 on 2024-10-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_flightprice_price_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightprice',
            name='price_history',
        ),
        migrations.AddField(
            model_name='flight',
            name='price_history',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
