# Generated by Django 5.1.1 on 2024-10-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_flightprice_price_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='bag',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='passenger',
            name='email',
            field=models.EmailField(default='Unknown', max_length=254),
        ),
        migrations.AddField(
            model_name='passenger',
            name='email_add',
            field=models.EmailField(default='Unknown', max_length=254),
        ),
        migrations.AddField(
            model_name='passenger',
            name='first_name_add',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='passenger',
            name='last_name_add',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='passenger',
            name='middle',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='passenger',
            name='phone_number',
            field=models.CharField(default='Unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='passenger',
            name='phone_number_add',
            field=models.CharField(default='Unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='passenger',
            name='redress_number',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='passenger',
            name='suffix',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='passenger',
            name='travel_number',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='citizenship',
            field=models.CharField(default='citizenship', max_length=100),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Gender', max_length=6),
        ),
    ]
