# Generated by Django 5.1.1 on 2024-10-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_passenger_bag_passenger_email_passenger_email_add_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='airline',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='passenger',
            name='arrival_airport',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='passenger',
            name='arrival_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='departure_airport',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='passenger',
            name='departure_date',
            field=models.DateField(default='1000-01-01'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='departure_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='flight',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='passenger',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='passenger',
            name='taxes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='passenger',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
