# Generated by Django 5.1.1 on 2024-10-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_passenger_airline_passenger_arrival_airport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='departure_date',
            field=models.CharField(default='1000-01-01', max_length=20),
        ),
    ]
