# Generated by Django 5.1.1 on 2024-10-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_passenger_departure_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='arrival_time',
            field=models.CharField(default='00:00:00', max_length=20),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='departure_time',
            field=models.CharField(default='00:00:00', max_length=20),
        ),
    ]
