# Generated by Django 5.1.1 on 2024-10-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_passenger_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='booking_date',
            field=models.DateTimeField(),
        ),
    ]
