# Generated by Django 5.1.1 on 2024-11-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_ticket_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='flight',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
