# Generated by Django 5.1.1 on 2024-11-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_ticket_flight_alter_ticket_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='city_arrival',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='passenger',
            name='city_departure',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='passenger',
            name='country_arrival',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='passenger',
            name='country_departue',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
