# Generated by Django 5.1.1 on 2024-11-02 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_passenger_city_arrival_passenger_city_departure_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='city_arrival',
            new_name='cityArrival',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='city_departure',
            new_name='cityDeparture',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='country_arrival',
            new_name='countryArrival',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='country_departue',
            new_name='countryDepartue',
        ),
    ]
