# Generated by Django 5.1.1 on 2024-11-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_countrydepartue_passenger_countrydeparture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=12)),
                ('date', models.CharField(max_length=10)),
                ('ccv', models.CharField(max_length=3)),
            ],
        ),
    ]
