# Generated by Django 5.1.1 on 2024-11-03 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='passenger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.passenger'),
        ),
    ]
