# Generated by Django 5.1.1 on 2024-11-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_card_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.CharField(max_length=16),
        ),
    ]
