# Generated by Django 5.1.1 on 2024-11-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_card_ccv_alter_card_date_alter_card_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='seat_class',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
