# Generated by Django 5.1.1 on 2024-11-05 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_ticket_seat_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.JSONField(blank=True, default=list)),
                ('passenger', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.passenger')),
            ],
        ),
    ]
